server:
  port: 18055

spring:
  application:
    name: zuul-aggregation

eureka:
  client:
    service-url:
      defaultZone: http://localhost:18000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: routes, filters

# 饿加载
zuul:
  ribbon:
    eager-load:
      enabled: true
