server:
  port: 18041

logging:
  root: DEBUG

spring:
  application:
    name: micro-movie-hystrix-feign

eureka:
  client:
    service-url:
      defaultZone: http://localhost:18000/eureka/
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true