server:
  port: 18025

logging:
  root: DEBUG

spring:
  application:
    name: micro-movie-ribbon-custom

eureka:
  client:
    service-url:
      defaultZone: http://localhost:18000/eureka/
  instance:
    prefer-ip-address: true
