server:
  port: 18063
spring:
  application:
    name: config-server-auth

  cloud:
    config:
      server:
        git:
          uri: https://github.com/HooYann/icloud
          username: user
          password: 123456
          search-paths: config/config-repository
          default-label: master
